on:
  push:
    branches: [ "production" ]
jobs:
  job1:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: 📂 Sync demo files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.peanalysis.com
          username: karincayuvasi@karincayuvasi.com
          password: ${{ secrets.ftp_password }}
          server-dir: api.demo.karincayuvasi.com/
      - name: Setup Migration with Rest Api
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.setup_token_demo }}" \
          https://api.demo.karincayuvasi.com/api/setup \
